#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/94dd7cc0-ab24-4aa7-823b-dd94edb7ac81 # 
title: Sales API

version: v1
mediaType: [application/json]

description: This API spec is designed to accept Opportunities and OpportunityLineItems to create Orders

types:
  opportunityLineItem:
    type: object
    properties: 
      ProductCode:
        type: string
      Quantity:
        type: number
    example: |
      {
        "ProductCode": "ABC001",
        "Quantity": 23.0
      }
  opportunity: 
    type: object
    properties: 
      OpportunityID:
        type: string
        example: "xxxxxx"
      CustomerID:
        type: string
        example: "xxxxxx"
      OpportunityLineItems:
        type: array
        items: opportunityLineItem
  orderCreatedResponse:
    type: object
    properties:
      resultCode:
        type: string
        example: "200"
      message:
        type: string
        example: "all good"
      OrderId:
        type: string
        example: "xx-0012-ss"
      CustomerID:
        type: string
        example: "xxxxx"
      OpportunityID:
        type: string
        example: "xxxxx"

/order:
  post:
    description: Creates a new order
    body: 
      application/json:
        type: opportunity
        example: |
          {
            "OpportunityID": "xxxxxx",
            "CustomerID": "xxxxxx",
            "OpportunityLineItems": [
              {
                "ProductCode": "ABC001",
                "Quantity": 23.0
              },
              {
                "ProductCode": "DEF001",
                "Quantity": 15.0
              }
            ]
          }
    responses: 
      200:
        body: 
          application/json:
            type: orderCreatedResponse
            example: |
              {
                "resultCode": "0",
                "message": "all good",
                "OrderId": "12312312312",
                "CustomerID": "xxxxxx",
                "OpportunityID": "xxxxxx"
              }