#%RAML 1.0
title: Sales API

version: v1

description: This API spec is designed to accept Opportunities and OpportunityLineItems to create Orders


mediaType: [application/json, application/xml]
securedBy: [passthrough]

securitySchemes: 
  passthrough: !include /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/pass-through-security-scheme/1.0.0/pass-through-security-scheme.raml

uses:
  sales-orders: /exchange_modules/66234019-5a31-4239-ba28-4e6d70f0468a/sales-orders-library/1.0.6/sales-orders-types.raml
  
/order:
  post:
    body:
      application/json:
        type: sales-orders.SalesOpportunity
    responses: 
      201:
        body:
          application/json:
            type: sales-orders.SalesOrderResponse 
      500:
        body:
          application/json:
            type: sales-orders.SalesOrderResponse  
